### ISSUE TITLE
Selecting elements by text

### ISSUE THREAD

**Issue by mikerrobinson** [natritmeyer/site_prism#10]
Does anyone think an additional method to select elements/sections by text would be helpful?  For example, say you have a list of users:

``` html
<ul>
    <li><strong>Luke Skywalker</strong></li>
    <li><strong>Darth Vader</strong></li>
    <li><strong>Han Solo</strong></li>
</ul>
```

And a sections definition:

``` ruby
section :users, UserSection, "ul li"
```

It might be nice to be able to select a subset of the elements via something like:

``` ruby
page.users_with_text("Darth Vader")
```

Pretty easy to implement using Capybara's find method, I would think.

Or, is it recommended to just parse through a returned array using normal ruby Array methods to find the same subset?

**Comment by dkniffin** [comment]
I know this is a very old issue, but I wanted to voice an objection to this opinion that selecting elements by text is bad. In my opinion, feature/integration tests that use capybara and site_prism should test things as close to the user's perspective as possible. User's do not know about CSS classes, ids, etc. All they see when they're viewing the page is the text and boxes and such. If I were to describe to a user how to navigate to something, I would not say "Click on the #button-homepage button" I would say "Click the button with the text "Homepage"".

This approach also has the advantage that it decouples the tests from the HTML structure a bit. If CSS classes or IDs change because of design or business decisions, but the button with that text is still on the page, the test does not break.
