### ISSUE TITLE
How to hover element in section

### ISSUE THREAD

**Issue by int18h** [natritmeyer/site_prism#114]
Hello, I try to hover element using myelement.hover and myelement.trigger(:mouseover) but got errors:
undefined method `trigger' for #<GC::TestObjects::ExperimentCard:0x007fb80b98c158> and undefined method`hover' for #GC::TestObjects::ExperimentCard:0x007fb80b98c158.

**Comment by natritmeyer** [comment]
Code examples? Stack traces?

**Comment by luke-hill** [comment]
Hi there. I'm going to be looking into the entire history list of issues e.t.c. and this one appears to be stale. Could you give a brief update as to what you plan to do with this.

If you plan to land a PR soon or already have done. Can you close this issue
If you think it's no longer relevant. Can you close this issue.

If possibly can you provide some update in the next couple of weeks (I'm aware this issue is several years old)
