### ISSUE TITLE
regex in html components id and names of buttons, text input, links

### ISSUE THREAD

**Issue by rmnscb** [natritmeyer/site_prism#124]
I am testing a web page , but the html components id and names of buttons, text input, links are automatically generated for each user and for each build.

Is it possible to identify an id and/or name using regex ?
Example of using regex:
element :search_field, "input[name='wt+(\d)+$wtUsername$+(\d)+$wtUserNameInput']"

example of dynamic and static fields of text input html name:
< static > < dynamic > < static > < dynamic > < static > 
 <wt> <713> <$wtUsername$wt> <234> <$wtUserNameInput>
wt713$wtUsername$wt234$wtUserNameInput

Example  html code -> text input:
user: John
 < input name="wt713$wtUsername$wt234$wtUserNameInput" type="text" maxlength="50" id="wt713$wtUsername$wt234$wtUserNameInput" tabindex="1" class="TextInput class-focus-out OSFillParent" onkeydown="return OsEnterKey('wt713_wtAction_wt234_wtSignInBtn', arguments[0] || window.event)" style="border-radius: 3px;" >

user Mary:
the same text input html code:
 < input name="wt362$wtUsername$wt45$wtUserNameInput" type="text" maxlength="50" id="wt362$wtUsername$wt45$wtUserNameInput" tabindex="1" class="TextInput class-focus-out OSFillParent" onkeydown="return OsEnterKey('wt362_wtAction_wt45_wtSignInBtn', arguments[0] || window.event)" style="border-radius: 3px;" >

**Comment by luke-hill** [comment]
Hi there. I'm going to be looking into the entire history list of issues e.t.c. and this one appears to be stale. Could you give a brief update as to what you plan to do with this.

If you plan to land a PR soon or already have done. Can you close this issue
If you think it's no longer relevant. Can you close this issue.

If possibly can you provide some update in the next couple of weeks (I'm aware this issue is several years old)
