### ISSUE TITLE
Using custom Capybara Query Selectors doesn't work

### ISSUE THREAD

**Issue by cantonic** [natritmeyer/site_prism#126]
I am trying to [use Capybara Query Selectors](https://github.com/natritmeyer/site_prism#using-capybara-query-options) with custom selectors that I have defined.

I have defined this custom selector:

``` ruby
Capybara.add_selector(:id) do
  xpath { |id| XPath.descendant[XPath.attr(:id) == id.to_s] }
end
```

But it seems that custom capybara selectors are not supported by site_prism, is that correct?

I am getting this error when trying to filter sections for by id:

```
ArgumentError: invalid keys :id, should be one of :count, :minimum, :maximum, :between, :text, :visible, :exact, :match, :wait
```

**Comment by tmertens** [comment]
@cantonic You are confusing [custom selectors](https://github.com/jnicklas/capybara#xpath-css-and-selectors) with [query options](https://github.com/natritmeyer/site_prism#using-capybara-query-options).  These are two separate features of Capybara, both of which SitePrism really just passes through to Capybara.  Defining a custom Capybara selector does NOT define a custom query option.

Probably you are passing your selector type incorrectly as a hash instead of as the first positional parameter:

```ruby
# This is INCORRECT and Capybara will read it as a Query Options hash:
element :foo, id: 123

# This is CORRECT
element :foo, :id, 123
```

**Comment by luke-hill** [comment]
Closing as old issue, pointers suggested
