### ISSUE TITLE
load_error isn't returning supplied message or any message

### ISSUE THREAD

**Issue by thompickett** [natritmeyer/site_prism#184]
class SomePage < SitePrism::Page
   load_validation { [wait_for_some_element(10) ,'Some error']}
   element :some_element, '#some_id'
end

If it can't find element currently

some_page.loaded? => false #This seems to be right according to docs
some_page.load_error => nil #This seems to be a bug, I would expect it to either raise 'Some error' or at least return it as a string

Am I doing something wrong? In our gemlock file we have version 2.9

**Comment by lastobelus** [comment]
ah. in this:
```ruby
    def load_validations_pass?
      self.class.load_validations.all? do |validation|
        passed, message = instance_eval(&validation)
        self.load_error = message if message && !passed
        passed
      end
    end
```

there needs to be parens around `message && !passed`

wise, grizzled old programmers like me learned long ago never to use order of precedence. If I ever make a language I will make it's expression order of precedence random so that all the whippersnappers learn that lesson.

also if you're using rspec, you'll have to wrap in a proc: `expect(page).to be_loaded, lambda { page.load_error }`

will try to make a pull request later

**Comment by tmertens** [comment]
> there needs to be parens around `message && !passed`

@lastobelus You are mistaken, sir.

@thompickett You likely have one of two problems:

Either:

1. whichever load validation is failing is not returning an error message or
2. your test code is accessing the `some_page.load_error` accessor method before the `some_page.loaded?` call.

Can you post the failing test code and point out the line where you are seeing a nil `load_error`?

**Comment by luke-hill** [comment]
Hi @thompickett Could you update us if this is still an issue and provide an SSCCE. If you don't think this is an issue any more could you close this Issue?

Thanks

Luke
