### ISSUE TITLE
No longer able to access Selenium Webdriver methods in site_prism 2.12

### ISSUE THREAD

**Issue by mnohai-mdsol** [natritmeyer/site_prism#255]
## Environment
- Operating System - ```Mac```
- What Gems / Versions - `site_prism 2.12` and `capybara 2.18`
- How you're interacting with the Framework - ```Cucumber```
- Browser/s Driver/s being used - Chrome 66, Chromedriver 2.38, Selenium Webdriver 3.11

## Expected Behavior
to be able to refresh the page using Selenium Webdriver using the following code.
```page.driver.browser.navigate.refresh```

## Actual Behavior
Get error ```protected method 'driver' called for #<Capybara::Node::Element... (NoMethodError)```

## Steps to reproduce
With the latest version of site_prism (2.12), try to use any of the Selenium Webdriver methods. I only specified one above. This worked fine on all previous versions.

**Comment by luke-hill** [comment]
Whilst you have provided a small reproducible script. I cannot get this to trigger my end (My company has many instances of calling selenium native methods - `page.driver.browser.action.stuff`

Did you find a specific update caused this issue to occur?
(If you have time) - Can you create a PR with a failing spec? (Just a cucumber one)
What kind of stacktrace are you seeing?

**Comment by mnohai-mdsol** [comment]
Yes, I apologize for not being as granular. This does occur in a section. Thanks!

**Comment by luke-hill** [comment]
Right. So this technically isn't an issue.

In `2.12` - we added a PR which fixed a long-standing bug. Whereby `page` was not correctly scoping. If you are inside a section. and call the following pseudo code.

`section.find(element)` - In <= 2.11 - It would search for `element` inside the physical whole visible DOM
`section.find(element)` - In 2.12 - It would search for `element` inside the section that has been scoped only.

However, this is done internally. So one caveat to this, is the way we have done this is to force `page` scoping to be at the level you are at (Section / Page)

Observation 1) You shouldn't be calling raw capybara code inside a cucumber test inside a section method. It should be at a page or World level.

Observation 2) To get around this (If you disagree with 1), you can rescope back to the page level by doing `Capybara.current_session`

Going forward into Capybara 3, we can potentially remove this slightly erroneous behaviour, because there will be a scoping method for libraries that wrap capybara.

I appreciate this perhaps isn't the resolution you were looking for, but I hope this at least explains the issue you are seeing, why you started seeing it in 2.12, and how you can avoid it by either not writing code in a certain way or amending your existing code.

NB) Calling `page` inside a `SitePrism::Page` object will be unnaffected, because no `root_element` is set so `Capybara.current_session` is the physically called method.
