### ISSUE TITLE
Create new release to accept last Capybara

### ISSUE THREAD

**Issue by manuelpuyol** [natritmeyer/site_prism#304]
Hi, version `2.15.1` only supports Capybara `< 3.3` and master branch already uses `< 3.6`
Any chance to release a new version to enable this latest support?

**Comment by luke-hill** [comment]
Closing as fixed with the 2.16 release. Note that the next likely release will be 3.0 alpha, no more 2.x feature releases are planned (Just bugfix ones)

**Comment by AnujaW** [comment]
hi  @luke-hill I am facing gem conflict errors while using site_prism gem (2.17) with  capybara (>= 1.1.2, < 4).
How long will it take to support Capybara version 3.5 or 3.7?

**Comment by luke-hill** [comment]
@AnujaW This issue has been closed as fixed with the 2.16 deploy.

I'm aware since that was the case there has been additional releases to the Capybara gem. However this ticket wouldn't be the place to raise them.

To surmise, there has been a lot less activity and demand for the updates to capybara functionality, other than the base (Enable 3.x), so we've stepped the increases slowly to ensure we don't break anything.

Full 3.x capybara compatibility will be forthcoming.
