### ISSUE TITLE
Filling inputs by label

### ISSUE THREAD

**Issue by evheny0** [natritmeyer/site_prism#337]
Hi!

Is there any way to describe input element strictly by labels, but not by css attributes? For example, using capybara I can fill input like that:
```ruby
fill_in "Some input label", text: "some text to fill"
```
but I don't see how can I do the same by `element` method.

**Comment by ineverov** [comment]
@evheny0 
https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/actions.rb#L91
`fill_in` method is, basically, find `fillable_field ` element and set value for it. You can do the same in site_prism defining your element like this
```ruby
class Page < SitePrism::Page
  element :my_labeled_element, :fillable_field, 'Some input label'
end

p = Page.new
p.load
p.my_labeled_element.set 'some text to fill'
```
If you want to use `fillable_field` locator by default **(I would not recommend it)** you can do
`Capybara.default_selector = :fillable_field` in your helper

**Comment by luke-hill** [comment]
You could also use a plethora of other values. Remembering that the hashable query options passed into site_prism finders can be any capybara query-option (There's a good dozen or so I believe). So you could pass in the label as you've mentioned or other items.

If you weren't sure what it looked like you could have your locator be very generic like `'div'` or `'input'` which when quantified with your text locator would work.

I'm going to close this as not an issue. But let me know if you think otherwise.
