### ISSUE TITLE
Bundle install requires ruby 2.3

### ISSUE THREAD

**Issue by nathan-menge-arcadia** [natritmeyer/site_prism#345]
# Issue to raise for SitePrism framework
I am working on a PR for Site Prism and encountered this error:

    [nate@Nates-MBP(eliminate_cause_of_warnings) ~/projects/ruby/site_prism]$ bundle install
Fetching gem metadata from https://rubygems.org/........
xpath-3.2.0 requires ruby version >= 2.3, which is incompatible with the current version, ruby 2.2.10p489

## Environment
- This is on osx, but is presumably universal?

Mainly I want to check if there are objections to bumping the .ruby-version to 2.3, given that latest stable is 2.5, this seems like it shouldn't be an issue, but I'm also not an open source project maintainer...

The alternative is to dig through the dependencies and see what version of what gem needs xpath, and at what point it could be restricted in version to not need ruby 2.3.

**Comment by luke-hill** [comment]
So the reason this has occurred is because in your current bundle you have set your ruby version via whatever manager you are using, and then you've done a full update.

In theory bundler shouldn't cause you any issues, because it should just pick the latest version you're compatible with on your current ruby version, but I know occassionally issues can crop up (We've seen it in travis).

Delete your lockfile and then re-run `bundle` and it'll all be fine. (Or should be, either way this is a bundling issue).

As for your 2nd point, objections to bumping the minimum ruby version. In essence we don't need to. As Capybara 3.1 forces ruby 2.3 and there currently are no ruby2.3 min criteria we use (Yet, there are plans to use some of the better non-legacy logger code going forward).

I'll put other comments on the PR as/when
