### ISSUE TITLE
Can't reuse SitePrism::Page objects across multiple Capybara::Sessions

### ISSUE THREAD

**Issue by mresnickmdlive** [natritmeyer/site_prism#360]
## Environment
- Operating System: Ubuntu Trusty (14.04) 
- Gem versions: site_prism 3.0.1, capybara 3.12.0
- Test framework: RSpec
- Driver info: selenium-webdriver gem 3.11.0, docker-selenium [hub@latest](https://hub.docker.com/r/selenium/hub/tags), docker-selenium [node-chrome@3.13](https://hub.docker.com/r/selenium/node-chrome/tags) 

## Expected Behavior
Reusing a single `SitePrism::Page` across multiple `Capybara::Session`s performs actions in the correct browser instance

## Actual Behavior
SitePrism::Page's `@page` is bound to the first Capybara::Session where the page object was used.

## Steps to reproduce
This script assumes that you have chromedriver installed and on your $PATH.
```ruby
require 'capybara/dsl'
require 'selenium-webdriver'
require 'site_prism'

Capybara.current_driver = :selenium_chrome

class Google < SitePrism::Page
  set_url 'https://www.google.com'
  element :privacy, '.Fx4vi', text: 'Privacy'
end

google = Google.new
google.load

Capybara.using_session('session2') do
  google.load
  google.privacy.click
end

raise "I'm on the privacy page, which should be in the other browser" unless google.displayed?
```

**Comment by luke-hill** [comment]
My knowledge on separate sessions is quite limited, @twalpole , but in essence 2 sessions should be 2 separate browser instances right? This feels like a bug but I'm not 100% sure.

Do the sessions have to be named according to the driver (So in this instance `:selenium_chrome`)

**Comment by twalpole** [comment]
@luke-hill Yes - each session is a separate browser instance.  The issue here is that any Capybara objects cached in SitePrism object could be from the wrong session if a SitePrism object is used in multiple sessions.  In this specific case I believe it's https://github.com/natritmeyer/site_prism/blob/master/lib/site_prism/page.rb#L34 where the actual session is cached in a SitePrism object.  I think there's really 3 possible solutions

1.  Acknowledge SitePrism objects shouldn't be used in multiple sessions (documentation)
2. Don't cache Capybara objects in SitePrism classes - code change
3. Implement session specific storage for any cached objects - code change

**Comment by luke-hill** [comment]
Cheers Thomas.

I actually remember when that code was implemented (Around 1year ago), and modified (2 weeks ago), to avoid Ruby 2.6 warnings about unused iVars.

For us to undo that code change is really simple. Because site_prism in the entire 2.x series ran without it.

Qu 1) What do you think we should do?

Qu 2) Do you think some sort of config switch here would be appropriate?

Qu 3) The change definitely needs to happen on site_prism right?

**Comment by luke-hill** [comment]
Yeh I think thats where I will change it, Ironically that was changed "from" the former to the latter quite recently. Because of a ruby2.6 warning about un-initialised constants. That's why we're only just hearing about it now.
