### ISSUE TITLE
Add find section by element text method and find element with text method to page and section

### ISSUE THREAD

**Issue by wizztjh** [natritmeyer/site_prism#91]
Hi,
I plan add a method `find_<sections_name>_by<element_name>and_<element_name>`  method to find the section with by element text.

Say the following code

``` ruby
class HomePage < SitePrism::Page
  sections :locations, Location, '.location-row'
end

class Location
  element :name, '.name'
  element :description, '.description'
end

home_page = HomePage.new
location_section = home_page.find_location_section_by_name_and_description('katar', 'nice place')
```

`find_location_section_by_name_and_description` will find the location section with name equal to `katar` and description equal to `nice place` and returns it.

So as, `find_<element_name>_with_text( <expected_element_text> )` to find one element within elements based on the element text.

Say the following code

``` ruby
  class HomePage < SitePrism::Page
    elements :rows, '.row'
  end

  home_page = HomePage.new
  row = home_page.find_row_by_text('Okay!')

```

`find_row_by_text` will return a row with `Okay!` as text

Is it a good idea? Any suggestion for me?

**Comment by luke-hill** [comment]
Hi there. I'm going to be looking into the entire history list of issues e.t.c. and this one appears to be stale. Could you give a brief update as to what you plan to do with this.

If you plan to land a PR soon or already have done. Can you close this issue
If you think it's no longer relevant. Can you close this issue.

If possibly can you provide some update in the next couple of weeks (I'm aware this issue is several years old)

**Comment by luke-hill** [comment]
Technically this is already possible in the newer Capybara API's (As this was an old issue I'm going to assume you couldn't easily do it there). 

Prefer not duplicating their API code and as such will be closing this issue
